### ISSUE TITLE
Missing support for Linux and OS X.

### ISSUE THREAD

**Issue by astrohome** [ubis/STM32duino-PlatformIO#1]
The "win" folder is just hardcoded into the scripts, and the path separator is windows only. So nothing work for Linux/OSX.

**Comment by ubis** [comment]
It should be only for flashing, so code should be compiled. But I will look into it.

**Comment by astrohome** [comment]
You are right, it's only for flashing.

**Comment by ubis** [comment]
Please update to the latest commit and check if it works.
Serial flash works here on Win/Linux, not tested on Mac, but should work aswell.

**Comment by astrohome** [comment]
It seems much better, but now I got:

`Auto-detected: /dev/ttyACM0
/home/astrohome/.platformio/packages/framework-stm32duino/tools/linux/serial_upload ttyACM0 {upload.altID} {upload.usbID} /home/astrohome/code/arduino/meteostation/.pioenvs/f103rb/firmware.bin
Failed to init device.
stm32flash Arduino_STM32_0.9`

I am using Maple Mini board (not the official one, but it works in Arduino IDE with STM32 installed), the exact board is STM32F103RCBT6

Should I follow some specific manipulations before flashing?

**Comment by ubis** [comment]
Which upload method do you use with Arduino IDE?
This one, serialflash is for MCU's, which have a pre-loaded bootloader(from manufacturer).
Since I'm using STM32F103RB, my boot modes are: Boot1(0), Boot0(1) and since I'm using simple FT232RL UART-USB, it doesn't reset mcu before flashing starts, I need to reset it manually.

If it works with Arduino IDE, it should work with PlatformIO aswell(if serial upload is chosen).
However, I will add support for STLink and other methods in near future.

**Comment by astrohome** [comment]
Ok, I see. In Arduino IDE I'm using dfu-util to flash via build-in usb port. That's not the same method you are using.

**Comment by ubis** [comment]
Could you go to Arduino IDE -> File> Preferences -> check box on "upload";
Upload sketch to your board and upload log in the bottom of Arduino IDE to pastebin.com or so?

Would be nice to see, what it shows when upload is successful and which file it uses from tools folder.

**Comment by astrohome** [comment]
Here we go: [http://pastebin.com/JWxCeHxb](url)

**Comment by ubis** [comment]
I did some modifications, although I might forgot something.
Let me know, if now DFU uploading works.

By the way, by default, it will use serial method, to use dfu:

- open platformio.ini (in your project folder)
- write: **upload_protocol = dfu**
- write: **upload_flags = 1** or **upload_flags = 2** (in your case, it should be 1.

**Comment by albertoferna** [comment]
ok. Halfway there.
I manage to get dfu-util working with a firmware compiled in platformio. I had to build a new specification for a different board to be able to use the maple bootloader.
I have a different problem now, with the changes I've made, platformio tries to upload using serial_upload instead of maple_upload. I guess I have to dig a littler deeper into how boards are defined. Any clues that may help me?
